services:
  db:
    image: mysql:8.0
    container_name: osticket-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: osticket-web
    restart: always
    ports:
      - "${WEB_PORT}:80"
    env_file: .env
    volumes:
      - osticket_files:/var/www/html
    depends_on:
      - db

volumes:
  db_data:
  osticket_files: